server:
  port: 8000
spring:
  application:
    name: hello-service
  boot:
    admin:
      client:
        url: http://localhost:9000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'



