
spring:
  profiles:
    active: default
  application:
    name: gateway
  boot:
    admin:
      client:
        url: http://localhost:9000
server:
  port: 11000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    helloservice : helloservice/**
    licensingservice : licensingservice/**
  include-debug-header: true
logging:
  level:
    com.cloud : debug


---







