spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
  application:
    name: api-redis
server:
  port: 8889
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka