

spring:
  application:
    name: eureka-service
server:
  port: 10000
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

---


