server:
  port:

---
spring:
  profiles: development
  application:
    name: eureka-service


server:
  port: 1000
eureka:
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: true

  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoint:
    web:
      exposeure:
        include: *




---